---
- name: Install main
  hosts:
    - main
  sudo: yes
  roles:
    - common
    - postgres
    - redis
      #    - tomcat
      #    - solr
      #    - nginx
      #    - role: vecnet
      #      rails:
      #        env: production
      #

- name: Install workers
  hosts:
    - workers
  sudo: yes
  roles:
      - common
      - fits
      - ruby
      #    - role: vecnet
      #      rails:
      #        env: production


- name: Install standalone
  hosts:
    - standalone
  sudo: yes
  roles:
      - common
      - postgres
      - tomcat
      - solr
      - nginx
      - fits
      - ruby
      - discovery

# The geosuite role needs some adjustement
# to configure the geoserver (it needs to
# change the redirect address and port)
#
#- name: Install geoserver
#  hosts: geoserver
#  sudo: yes
#  roles:
#    - common
#    - geosuite
