---
- name: Install main
  hosts:
    - main
  sudo: yes
  roles:
    - common
    - postgres
    - redis
      #- tomcat
      #- solr
      #- nginx
      #- discovery
      #- vecnet
      #
      # - fedora?
      # - disadis
      # - noids
      # - runit
      # - backup rsync
      #

- name: Install workers
  hosts:
    - workers
  sudo: yes
  roles:
      - common
      - fits
      - ruby
      #- vecnet

- name: Install standalone
  hosts:
    - standalone
  sudo: yes
  roles:
      - common
      - postgres
      - tomcat
      - solr
      - fedora
      - nginx
      - redis
      - noids
      - fits
      - ruby
      - discovery
      - vecnet

# The geosuite role needs some adjustement
# to configure the geoserver (it needs to
# change the redirect address and port)
#
#- name: Install geoserver
#  hosts: geoserver
#  sudo: yes
#  roles:
#    - common
#    - geosuite
