# See also http://mvnrepository.com/artifact/org.fcrepo/fcrepo-webapp-fedora/${fedora_version}
---
# incorporate this into how other roles do this
- file: path=/opt/src state=directory

- name: Check variable fedora_version is set
  fail: msg="Please set 'fedora_version' variable in the playbook"
  when: fedora_version is not defined

- name: Download Fedora Commons
  get_url: >
      url={{ fedora_cache_url }}/fcrepo-installer-{{ fedora_version }}.jar
      dest=/opt/pkg/fcrepo-installer-{{ fedora_version }}.jar
      owner=tomcat
      group=tomcat
#shell: curl http://repo1.maven.org/maven2/org/fcrepo/fcrepo-installer/{{fedora_version}}/fcrepo-installer-{{fedora_version}}.jar > /tmp/fcrepo-installer-{{fedora_version}}.jar creates=/tmp/fcrepo-installer-{{fedora_version}}.jar

- name: Upload install.properties file for automated install
  template: >
      src=fedora-install-properties.j2
      dest=/opt/src/fedora-install.properties
      owner=tomcat
      group=tomcat

- name: Setup directory
  file: >
      path=/opt/fedora
      state=directory
      owner=tomcat
      group=tomcat

- name: Run automated install of fedora-commons
  command: >
      java -jar /opt/pkg/fcrepo-installer-{{ fedora_version }}.jar /opt/src/fedora-install.properties
      creates=/opt/fedora/server/config/fedora.fcfg

- name: set file owner to tomcat
  file: >
      path=/opt/fedora
      owner=tomcat
      group=tomcat
      recurse=yes

# TODO: make this square with how things are done already on the server
# disable default xacml policy of denying everything except localhost
- name: remote apim xacml (server default)
  file: >
    path=/opt/fedora/server/fedora-internal-use/fedora-internal-use-repository-policies-approximating-2.0/deny-apim-if-not-localhost.xml
    state=absent
- name: remote apim xacml (repo data policies)
  file: >
    path=/opt/fedora/data/fedora-xacml-policies/repository-policies/default/deny-apim-if-not-localhost.xml
    state=absent

- name: setup akubra data path
  template: >
      src=akubra-llstore.xml.j2
      dest=/opt/fedora/server/config/spring/akubra-llstore.xml
      owner=tomcat
      group=tomcat

# deploy the fedora context last
- name: Install tomcat context for fedora
  template: >
      src=fedora-xml.j2
      dest=/etc/tomcat6/Catalina/localhost/fedora.xml
      owner=tomcat
      group=tomcat
