---
vecnet_deploy_root: /opt/vecnet-dl
rails_env: development
fedora_password: fedoraAdmin
solr_service_addr: http://localhost:8081/solr
db_hostname: localhost
db_name: vecnet_db
db_user: vecnet
db_password: vecnet
