---
- name: Add ferm config directorys
  file: >
    path={{ item }}
    state=directory
    owner=root group=root mode=0700
  with_items:
    - /etc/ferm
    - /etc/ferm/ferm.d

- name: Copy ferm config
  copy: >
    src=ferm.conf
    dest=/etc/ferm/ferm.conf
    owner=root group=root mode=0700
  notify:
    - run ferm

